export const SkillList = [
    {
        name:"CSS",
        x: '-5vw',
        y: '-12vw',
        i:0
    },
    {
        name:"HTML",
        x:"-30vw",
        y:"2vw",
        i:1
    },
    {
        name:"Java",
        x:"-18vw",
        y:"3vw",
        i:2
    },
    {
        name:"Python",
        x:"18vw",
        y:"14vw",
        i:3
    },
    {
        name:"React",
        x:"8vw",
        y:"7vw",
        i:4
    },
    {
        name:"JavaScript",
        x:"-3vw",
        y:"-24vw",
        i:5
    },
    {
        name:"NextJS",
        x:"-25vw",
        y:"-8vw",
        i:6
    },
    {
        name:"C#",
        x:"5vw",
        y:"19vw",
        i:7
    },
    {
        name:"Figma",
        x:"5vw",
        y:"19vw",
        i:8
    },
    {
        name:"Unity",
        x:"26vw",
        y:"-8vw",
        i:9
    },
    {
        name:"Git",
        x:"10vw",
        y:"-6vw",
        i:10
    },
    {
        name:"Phabricator",
        x:"-5vw",
        y:"13vw",
        i:11
    },
    {
        name:"TailwindCSS",
        x:"-10vw",
        y:"22vw",
        i:12
    },
    {
        name:"Microsoft Office",
        x:"10vw",
        y:"-16vw",
        i:13
    },
    {
        name:"Visual Studio",
        x:"-20vw",
        y:"-17vw",
        i:14
    },
    {
        name:"C++",
        x:"-22vw",
        y:"12vw",
        i:15
    }
]